services:
  token-server:
    build: .
    # image: fast-token-server:latest
    container_name: fast-token-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TOKENIZER_PATH=/app/tokenizer.json  # path in container
      - MAX_TEXT_LENGTH=200000  # length characters --> Deprecated
      - CACHE_TTL_SECONDS=300
      - REDIS_URL=redis://redis:6379/0        # <-- báº­t Redis
    volumes:
      - ./tokenizer.json:/app/tokenizer.json:ro
    command: ["uvicorn", "token_server:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]

  # redis:
  #   image: redis:7-alpine
  #   container_name: fast-token-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

# volumes:
#   redis-data: {}
